### ISSUE TITLE
Is this repo been tested?

### ISSUE THREAD

**Issue by wangdelp** [kyegomez/CM3Leon#4]
I've encountered lots of errors like unfound attributes etc, wonder is this repo has been tested?

**Comment by kyegomez** [comment]
@wangdelp Hey 

What errors are you encountering?

Nope it has not been tested as much as I'd like to test it because I don't have access to my cluster of a100s right now and testing it on my mac would be pointless since it wouldn't run on GPU.

**Comment by wangdelp** [comment]
@kyegomez 
Attribute errors like `AttributeError: 'ViTransformerWrapper' object has no attribute 'patch_to_embeding'`
And the latest error is:
`CM3Leon/cm3/core/autoregressive_wrapper.py", line 128, in forward
    seq, ignore_index = x.shape[1], self.ignore_index
IndexError: tuple index out of range`.

I guess testing on Mac is still meaningful to make it runnable first, before consideration of speed which needs GPU access?

**Comment by kyegomez** [comment]
@wangdelp 

Thanks 🙏, yeah I agree. 

This is a bad habit I picked up, I need to test a lot more my brain jumps from one project to the next at light speed with errors in the previous creating a mess.

Please excuse me

**Comment by kyegomez** [comment]
@wangdelp  I just solved some errors, it should work now. My mac started shaking and went out memory very quick, let me know if there any other issues, I am here for you!.


Bug 1: AttributeError: 'ViTransformerWrapper' object has no attribute 'patch_to_embeding'
Description:
The 'ViTransformerWrapper' object was trying to access an attribute 'patch_to_embeding' which did not exist.

Solution:
The attribute name was likely misspelled. It should be 'patch_to_embedding' instead of 'patch_to_embeding'. The attribute name was corrected in the code.

Bug 2: IndexError: tuple index out of range
Description:
The code was trying to access an index that did not exist in the tuple x.shape.

Solution:
Added a check to ensure that x has at least two dimensions before trying to access x.shape[1]. If x is a 1D tensor, an error message is raised.

Bug 3: TypeError: randint(): argument 'size' (position 2) must be tuple of ints, not int
Description:
The torch.randint() function was called with an integer as the second argument, but it expects a tuple to specify the size of the output tensor.

Solution:
Changed the second argument of torch.randint() to a tuple. For example, if a 1D tensor with one element is needed, the corrected line is caption_tokens = torch.randint(0, 4, (1,)).

Bug 4: AttributeError: cannot assign module before Module.init() call
Description:
A module was assigned before calling the parent class's __init__() method.

Solution:
Moved the super().__init__() call to the beginning of the __init__() method to ensure that the necessary setup is done before assigning submodules.

**Comment by rsxdalv** [comment]
Any idea how much RAM is needed? When testing I saw more than 12GBs being required.

**Comment by wangdelp** [comment]
Thanks, there is one more issue in the example, it should be `output = model(img, text)
` instead of `output = model(text, img)
`.

@rsxdalv I am seeing 24GB memory usage, you may reduce the model size to smaller like the 760M setting (depth=24, dim=1536)

**Comment by wangdelp** [comment]
I am trying to export the model using coreml, but hit into the error below: `    raise ValueError(
ValueError: Incompatible dim 1 in shapes (1, 64, 1536) vs. (1, 1536, 1536)`.

here is my program for export, any idea what goes wrong?

`if __name__ == "__main__":
    img = torch.randn(1, 3, 256, 256)
    text = torch.randint(0, 20000, (1, 1024))
    
    model = CM3()
    # output = model(None, text)
    output = model(img, text)
    print(output)
    traced_optimized_model = torch.jit.trace(model, (img, text))

    import coremltools as ct
    import numpy as np
    ane_mlpackage_obj = ct.convert(
        traced_optimized_model,
        convert_to="mlprogram",
        inputs=[
            ct.TensorType("img", shape=img.shape),
            ct.TensorType("text", shape=text.shape),
            ],
    )
    out_path = "mha.mlpackage"
    ane_mlpackage_obj.save(out_path)`

**Comment by rsxdalv** [comment]
> 

Thanks, I was able to load it and push it to GPU.

I did get an error when I tried to run it, but I will open a separate issue for that.

**Comment by kyegomez** [comment]
@rsxdalv 

Based on the comments, it seems like you were testing a model and noticed that it required more than 12GB of RAM. In response, wangdelp suggested reducing the model size to decrease memory usage. Specifically, @wangdelp  mentioned trying the 760M setting with a depth of 24 and a dimension of 1536.

@wangdelp 

Regarding your export issue, the error message indicates an incompatible dimension between (1, 64, 1536) and (1, 1536, 1536). It seems like there is a mismatch between the dimensions of the input and output tensors of your model when converting it to CoreML.

To resolve this issue, double-check the shapes of your tensors and ensure they match the expected dimensions. Also, make sure you are passing the correct inputs to the torch.jit.trace() method.


I have reversed the input params of the forward pass of the model so it's like

model(text_tokens, image)

 - (text first, image) next
